### ISSUE TITLE
最新固件2023.02.24 NanoPi-R5S-R5C-linux.6.1无法启动Docker

### ISSUE THREAD

**Issue by antbuster** [DHDAXCW/NanoPi-R5S-R5C#43]
使用的是
docker-friendlyarm_nanopi-r5c-ext4-sysupgrade.img.gz
docker-friendlyarm_nanopi-r5c-squashfs-sysupgrade.img.gz
纯净系统，无开启任何插件
显示【无法连接到docker守护进程（docker daemon），请检查!!】
系统错误日志如下

`Sun Feb 26 20:41:35 2023 kern.err kernel: [  229.949100] SQUASHFS error: Unable to read data cache entry [2bc6cba]
Sun Feb 26 20:41:35 2023 kern.err kernel: [  229.949684] SQUASHFS error: Unable to read page, block 2bc6cba, size 3f8e8
Sun Feb 26 20:41:36 2023 kern.err kernel: [  229.991232] SQUASHFS error: Unable to read data cache entry [2bc6cba]
Sun Feb 26 20:41:36 2023 kern.err kernel: [  229.991823] SQUASHFS error: Unable to read page, block 2bc6cba, size 3f8e8
Sun Feb 26 20:41:36 2023 kern.err kernel: [  229.992534] SQUASHFS error: Unable to read data cache entry [2bc6cba]
Sun Feb 26 20:41:36 2023 kern.err kernel: [  229.993104] SQUASHFS error: Unable to read page, block 2bc6cba, size 3f8e8
Sun Feb 26 20:41:36 2023 kern.err kernel: [  229.993835] SQUASHFS error: Unable to read data cache entry [2bc6cba]
Sun Feb 26 20:41:36 2023 kern.err kernel: [  229.994586] SQUASHFS error: Unable to read page, block 2bc6cba, size 3f8e8
Sun Feb 26 20:41:36 2023 kern.err kernel: [  229.996041] SQUASHFS error: Unable to read data cache entry [2bc6cba]
Sun Feb 26 20:41:36 2023 kern.err kernel: [  229.996624] SQUASHFS error: Unable to read page, block 2bc6cba, size 3f8e8
Sun Feb 26 20:41:36 2023 kern.err kernel: [  229.997236] SQUASHFS error: Unable to read data cache entry [2bc6cba]
Sun Feb 26 20:41:36 2023 kern.err kernel: [  229.997801] SQUASHFS error: Unable to read page, block 2bc6cba, size 3f8e8
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: unexpected fault address 0xaaaad50a6d70
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: fatal error: fault
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: [signal SIGBUS: bus error code=0x2 addr=0xaaaad50a6d70 pc=0xaaaad50a6d70]
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]:
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: goroutine 1 [running, locked to thread]:
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.throw({0xaaaad51da6ba?, 0x0?})
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/panic.go:1047 +0x40 fp=0x400063fa30 sp=0x400063fa00 pc=0xaaaad4227670
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.sigpanic()
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/signal_unix.go:832 +0xa4 fp=0x400063fa60 sp=0x400063fa30 pc=0xaaaad423ead4
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: github.com/vishvananda/netlink.init()
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/build_dir/target-aarch64_generic_musl/containerd-1.6.6/.go_work/build/src/github.com/containerd/containerd/vendor/github.com/vishvananda/netlink/conntrack_linux.go:454 fp=0x400063fa70 sp=0x400063fa70 pc=0xaaaad50a6d70
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.doInit(0xaaaad6358ca0)
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/proc.go:6329 +0x12c fp=0x400063fbb0 sp=0x400063fa70 pc=0xaaaad4237b0c
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.doInit(0xaaaad636ca80)
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/proc.go:6306 +0x68 fp=0x400063fcf0 sp=0x400063fbb0 pc=0xaaaad4237a48
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.doInit(0xaaaad635b9e0)
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/proc.go:6306 +0x68 fp=0x400063fe30 sp=0x400063fcf0 pc=0xaaaad4237a48
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.doInit(0xaaaad6360800)
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/proc.go:6306 +0x68 fp=0x400063ff70 sp=0x400063fe30 pc=0xaaaad4237a48
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.main()
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/proc.go:233 +0x1f8 fp=0x400063ffd0 sp=0x400063ff70 pc=0xaaaad4229c28
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.goexit()
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/asm_arm64.s:1172 +0x4 fp=0x400063ffd0 sp=0x400063ffd0 pc=0xaaaad425b6c4
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]:
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: goroutine 2 [force gc (idle)]:
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/proc.go:363 +0xe4 fp=0x4000058fa0 sp=0x4000058f80 pc=0xaaaad422a044
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.goparkunlock(...)
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/proc.go:369
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.forcegchelper()
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/proc.go:302 +0xac fp=0x4000058fd0 sp=0x4000058fa0 pc=0xaaaad4229edc
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.goexit()
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000058fd0 sp=0x4000058fd0 pc=0xaaaad425b6c4
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: created by runtime.init.6
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/proc.go:290 +0x24
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]:
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: goroutine 18 [GC sweep wait]:
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/proc.go:363 +0xe4 fp=0x4000054770 sp=0x4000054750 pc=0xaaaad422a044
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.goparkunlock(...)
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/proc.go:369
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.bgsweep(0x0?)
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/mgcsweep.go:297 +0x10c fp=0x40000547b0 sp=0x4000054770 pc=0xaaaad4214d9c
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.gcenable.func1()
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/mgc.go:178 +0x28 fp=0x40000547d0 sp=0x40000547b0 pc=0xaaaad4209328
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.goexit()
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40000547d0 sp=0x40000547d0 pc=0xaaaad425b6c4
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: created by runtime.gcenable
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/mgc.go:178 +0x74
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]:
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: goroutine 19 [sleep]:
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.gopark(0x4000096000?, 0x35c85c326c?, 0x0?, 0x0?, 0xaaaad57f9ce8?)
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/proc.go:363 +0xe4 fp=0x4000054f10 sp=0x4000054ef0 pc=0xaaaad422a044
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.goparkunlock(...)
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/proc.go:369
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.(*scavengerState).sleep(0xaaaad63bf480, 0x41105c3800000000)
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/mgcscavenge.go:468 +0x120 fp=0x4000054f80 sp=0x4000054f10 pc=0xaaaad4212f10
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.bgscavenge(0x0?)
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/mgcscavenge.go:626 +0x9c fp=0x4000054fb0 sp=0x4000054f80 pc=0xaaaad42132ec
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.gcenable.func2()
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/mgc.go:179 +0x28 fp=0x4000054fd0 sp=0x4000054fb0 pc=0xaaaad42092c8
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.goexit()
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000054fd0 sp=0x4000054fd0 pc=0xaaaad425b6c4
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: created by runtime.gcenable
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/mgc.go:179 +0xb8
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]:
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: goroutine 20 [finalizer wait]:
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.gopark(0x600000000085f8?, 0xaaaad42066d8?, 0xb8?, 0x75?, 0x2000000000?)
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/proc.go:363 +0xe4 fp=0x4000058580 sp=0x4000058560 pc=0xaaaad422a044
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.goparkunlock(...)
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/proc.go:369
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.runfinq()
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/mfinal.go:180 +0x120 fp=0x40000587d0 sp=0x4000058580 pc=0xaaaad4208550
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.goexit()
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40000587d0 sp=0x40000587d0 pc=0xaaaad425b6c4
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: created by runtime.createfing
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/mfinal.go:157 +0x84
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]:
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: goroutine 34 [GC worker (idle)]:
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.gopark(0x358c6ea7da?, 0x3?, 0xb9?, 0xdd?, 0x7?)
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/proc.go:363 +0xe4 fp=0x4000055740 sp=0x4000055720 pc=0xaaaad422a044
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.gcBgMarkWorker()
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/mgc.go:1235 +0xec fp=0x40000557d0 sp=0x4000055740 pc=0xaaaad420b70c
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.goexit()
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40000557d0 sp=0x40000557d0 pc=0xaaaad425b6c4
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: created by runtime.gcBgMarkStartWorkers
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/mgc.go:1159 +0x28
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]:
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: goroutine 3 [GC worker (idle)]:
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/proc.go:363 +0xe4 fp=0x4000059740 sp=0x4000059720 pc=0xaaaad422a044
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.gcBgMarkWorker()
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/mgc.go:1235 +0xec fp=0x40000597d0 sp=0x4000059740 pc=0xaaaad420b70c
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.goexit()
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40000597d0 sp=0x40000597d0 pc=0xaaaad425b6c4
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: created by runtime.gcBgMarkStartWorkers
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/mgc.go:1159 +0x28
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]:
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: goroutine 35 [GC worker (idle)]:
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.gopark(0x358c5d7d7c?, 0x0?, 0x0?, 0x0?, 0x0?)
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/proc.go:363 +0xe4 fp=0x4000492740 sp=0x4000492720 pc=0xaaaad422a044
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.gcBgMarkWorker()
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/mgc.go:1235 +0xec fp=0x40004927d0 sp=0x4000492740 pc=0xaaaad420b70c
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.goexit()
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40004927d0 sp=0x40004927d0 pc=0xaaaad425b6c4
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: created by runtime.gcBgMarkStartWorkers
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/mgc.go:1159 +0x28
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]:
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: goroutine 4 [GC worker (idle)]:
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.gopark(0x358c5d832e?, 0x0?, 0x0?, 0x0?, 0x0?)
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/proc.go:363 +0xe4 fp=0x4000059f40 sp=0x4000059f20 pc=0xaaaad422a044
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.gcBgMarkWorker()
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/mgc.go:1235 +0xec fp=0x4000059fd0 sp=0x4000059f40 pc=0xaaaad420b70c
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.goexit()
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000059fd0 sp=0x4000059fd0 pc=0xaaaad425b6c4
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: created by runtime.gcBgMarkStartWorkers
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/mgc.go:1159 +0x28
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]:
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: goroutine 5 [chan receive]:
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.gopark(0x400005aef8?, 0xaaaad425814c?, 0x0?, 0xcf?, 0x4000318008?)
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/proc.go:363 +0xe4 fp=0x400005aea0 sp=0x400005ae80 pc=0xaaaad422a044
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.chanrecv(0x40000941e0, 0x400005af90, 0x1)
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/chan.go:583 +0x454 fp=0x400005af30 sp=0x400005aea0 pc=0xaaaad41f6964
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.chanrecv2(0x12a05f200?, 0x0?)
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/chan.go:447 +0x14 fp=0x400005af60 sp=0x400005af30 pc=0xaaaad41f64f4
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: k8s.io/klog/v2.(*loggingT).flushDaemon(0x0?)
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/build_dir/target-aarch64_generic_musl/containerd-1.6.6/.go_work/build/src/github.com/containerd/containerd/vendor/k8s.io/klog/v2/klog.go:1181 +0x5c fp=0x400005afb0 sp=0x400005af60 pc=0xaaaad4a399dc
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: k8s.io/klog/v2.init.0.func1()
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/build_dir/target-aarch64_generic_musl/containerd-1.6.6/.go_work/build/src/github.com/containerd/containerd/vendor/k8s.io/klog/v2/klog.go:420 +0x28 fp=0x400005afd0 sp=0x400005afb0 pc=0xaaaad4a37418
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: runtime.goexit()
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/staging_dir/hostpkg/lib/go-cross/src/runtime/asm_arm64.s:1172 +0x4 fp=0x400005afd0 sp=0x400005afd0 pc=0xaaaad425b6c4
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: created by k8s.io/klog/v2.init.0
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: 	/home/d/r5s/_work/NanoPi-R5S-R5C/NanoPi-R5S-R5C/openwrt/build_dir/target-aarch64_generic_musl/containerd-1.6.6/.go_work/build/src/github.com/containerd/containerd/vendor/k8s.io/klog/v2/klog.go:420 +0x150
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: time="2023-02-26T20:41:36.032903018+08:00" level=error msg="containerd did not exit successfully" error="exit status 2" module=libcontainerd
Sun Feb 26 20:41:36 2023 daemon.err dockerd[14049]: time="2023-02-26T20:41:36.956187269+08:00" level=warning msg="grpc: addrConn.createTransport failed to connect to {unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = \"transport: error while dialing: dial unix:///var/run/docker/containerd/containerd.sock: timeout\". Reconnecting..." module=grpc
Sun Feb 26 20:41:39 2023 daemon.err dockerd[14049]: time="2023-02-26T20:41:39.262148561+08:00" level=warning msg="grpc: addrConn.createTransport failed to connect to {unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = \"transport: error while dialing: dial unix:///var/run/docker/containerd/containerd.sock: timeout\". Reconnecting..." module=grpc
Sun Feb 26 20:41:42 2023 daemon.err dockerd[14049]: time="2023-02-26T20:41:42.782576896+08:00" level=warning msg="grpc: addrConn.createTransport failed to connect to {unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = \"transport: error while dialing: dial unix:///var/run/docker/containerd/containerd.sock: timeout\". Reconnecting..." module=grpc
Sun Feb 26 20:41:48 2023 daemon.err dockerd[14049]: time="2023-02-26T20:41:48.078202899+08:00" level=warning msg="grpc: addrConn.createTransport failed to connect to {unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = \"transport: error while dialing: dial unix:///var/run/docker/containerd/containerd.sock: timeout\". Reconnecting..." module=grpc
Sun Feb 26 20:41:50 2023 daemon.err dockerd[14049]: failed to start containerd: timeout waiting for containerd to start`

**Comment by antbuster** [comment]
不是线刷的问题，线刷就没事。关了吧
